name: 'Promote docker image'
description: "Adds current branch tag and specified environment tag to a docker image. Determines source tag by examining PR that introduced the current commit."
inputs:
  tag:
    description: New tag to apply to image
    required: true
  add_ref_tag:
    description: Whether to apply a docker tag based on the current branch or github tag
    required: false
    default: "true"
  image_name:
    description: "Name of the docker image. Image will be available in the registry at a location such as 'us-docker.pkg.dev/build-artifacts-tools-b6f1/<repo-name>/<image_name>:<git_sha>'."
    required: false
    default: image
  base64_workload_identity_provider:
    description: "Google CLoud Workload Identity Provider"
    required: true
  base64_gcp_service_account:
    description: "Google Service Account"
    required: true
  base64_docker_registry:
    description: "Docker registry URI"
    required: true
outputs:
  unique_docker_tag:
    description: Docker tag of the image that got promoted. This is used when the stack also contains a consumer of this image. For example, when terraform deploys cloud run using the image promoted here, it should specify a unique tag, rather than an environment tag, in order to deploy atomicly.
    value: ${{ steps.fetch-sha.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Set up gcloud
      uses: vivantehealth/gcloud-workload-identity-action@v2
      with:
        base64_workload_identity_provider: ${{ inputs.BASE64_WORKLOAD_IDENTITY_PROVIDER }}
        base64_gcp_service_account: ${{ inputs.BASE64_GCP_SERVICE_ACCOUNT }}
    - name: Parse docker registry/repo
      shell: bash
      run: |
        repo=$(echo -n ${{ inputs.BASE64_DOCKER_REGISTRY }} | base64 -d)
        echo "DOCKER_REPO=$repo" >> $GITHUB_ENV
        echo "DOCKER_REGISTRY=$(echo -n ${repo} | sed 's/\/.*//')" >> $GITHUB_ENV
    - name: Configure Docker
      shell: bash
      run: |
        gcloud auth configure-docker ${{ env.DOCKER_REGISTRY }}
    # Get the head commit of the PR that introduced this commit. This is the
    # tag that should have been added to the docker image when it was built
    # and pushed
    - name: Get docker tag
      uses: actions/github-script@v6
      id: fetch-sha
      with:
        script: |
          const result = await github.rest.repos.listPullRequestsAssociatedWithCommit({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha:  context.sha
          });
          const prs = result.data.filter((pr) => pr.merged_at !== null && pr.merged_at !== "")
          if (prs.length !== 1) {
            throw new Error(`Expected exactly one merged PR introducing this commit. Found ${prs.length}`)
          }
          const sha = prs[0].head.sha
          return sha
    - name: Set source image tag
      shell: bash
      run: |
        echo "SOURCE_TAG=$(echo -n ${{ steps.fetch-sha.outputs.result}})" >> $GITHUB_ENV
        # There are extra quotes around the output from the fetch-sha step.
        # This should remove them and set as an env var for subsequent steps
    - name: Pull
      shell: bash
      run: |
        docker pull ${{ env.DOCKER_REPO }}/${{ inputs.image_name }}:${{ env.SOURCE_TAG }}
    - name: Tag and push
      shell: bash
      run: |
        registry=$(echo -n ${{ inputs.BASE64_DOCKER_REGISTRY }} | base64 -d)
        docker tag ${registry}/${{ inputs.image_name }}:${{ env.SOURCE_TAG }} ${registry}/${{ inputs.image_name }}:${{ inputs.tag }}
        docker push ${registry}/${{ inputs.image_name }}:${{ inputs.tag }}
    - name: Add ref tag
      if: ${{ github.event.inputs.add_ref_tag == 'true' }}
      shell: bash
      run: |
        docker tag ${registry}/${{ inputs.image_name }}:${{ env.SOURCE_TAG }} ${registry}/${{ inputs.image_name }}:${{ github.ref_name }}
        docker push ${registry}/${{ inputs.image_name }}:${{ github.ref_name }}
